# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.17

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  release:
    docker:
      - image: cimg/node:22.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: ./node_modules/.bin/semantic-release

workflows:
  test_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
